### ISSUE TITLE
Downloading is slow

### ISSUE THREAD

**Issue by moverlock1024** [JohnDoee/rippy#2]
Nice project! I wonder if we could boost the downloading speed. Maybe using multiple threads or tools like ariac2?

**Comment by moverlock1024** [comment]
~~Oh, this doesn't work properly when ripping from avgle. The actual mp4 file downloaded is somehow a random one. It doesn't related to the url given.~~


Tuning `      - RIPPY_CONCURRENCY=20
` doesn't have any positive effect on downloading speed. It's definitely sequential. The console prints `vnc_1     | 127.0.0.1 - - [2019-07-10 18:39:56] "GET /api/health HTTP/1.1" 200 122 0.130654` one by one.

**Comment by JohnDoee** [comment]
It uses ffmpeg built-in http client right now which is quite slow, one file at a time and I think it closes the connection between each file-segment.

the CONCURRENCY variable just increases the number of different videos you can download simultaneously.

I'll check if it's fast to add otherwise it might have to wait a bit.

**Comment by moverlock1024** [comment]
Cool. There is a project https://github.com/download-online-video/chrome-avgle-helper using aria2c to achieve parallel downloading w.r.t file segments, however it often encounters 403 due to CAPTCHA failures. I guess we might be able to use a similar aria2c command here?

**Comment by JohnDoee** [comment]
Pushed new image, 0.1.2, it should have the new downloader.

You can adjust the number of download threads for a single file now too in the docker-compose.yml file by adjusting RIPPY_DOWNLOAD_CONCURRENCY

**Comment by moverlock1024** [comment]
I just tried out the updated docker-compose file with `RIPPY_DOWNLOAD_CONCURRENCY = 20` but it still only used 1 thread to download. (avg speed is around 500KB per sec)

**Comment by JohnDoee** [comment]
Are you sure the docker container is updated ? try `docker pull johndoee/rippy:latest`

I'm getting very good speeds at high concurrency, it definitely works :smile:

**Comment by moverlock1024** [comment]
hmm, that's weird. I tried `docker pull johndoee/rippy:latest` but it didn't seem like to update anything, saying :
```
 ~  docker pull johndoee/rippy-vnc:latest
latest: Pulling from johndoee/rippy-vnc
Digest: sha256:3e858efb7967bbc7c61ace758a842e08c0f75417d8f416e8e8ccf79f7353914c
Status: Image is up to date for johndoee/rippy-vnc:latest
```

I guess there might still be something missing?

**Comment by JohnDoee** [comment]
That's the VNC image (I made a typo too), can you check to make sure the `johndoee/rippy:latest` is correct ?

    latest: Pulling from johndoee/rippy
    Digest: sha256:58a6b29e9299b55bfa36ee384dd73f41d133333f5c739df53254b6900cb6b597
    Status: Image is up to date for johndoee/rippy:latest

**Comment by moverlock1024** [comment]
Marvelous!  I hope there would be a flag for the docker-compose file to update related images as per https://github.com/docker/compose/issues/3574
