### ISSUE TITLE
Add a retry button

### ISSUE THREAD

**Issue by moverlock1024** [JohnDoee/rippy#3]
![image](https://user-images.githubusercontent.com/52660817/61515139-76395180-aa34-11e9-9d5a-c2fabecae0f4.png)

Currently the UI doesn't even allow me to copy the full url. Would love to have a retry button :)

**Comment by JohnDoee** [comment]
A retry button makes sense.

Can you retry it manually to see if it's a coding error in the project or just a random accident?

**Comment by moverlock1024** [comment]
I'm not sure how to retry it since the url is partially printed. The error is due to a premature shutdown of the rippy container.

**Comment by JohnDoee** [comment]
There's a retry button now. I also changed the docker-compose file to use exact version instead of "latest" and skipped pushing a new "latest".

Probably gonna delete that tag soon.
